Refactoring: Move add extension functionality into separate renderrelativemarkers action
With the idea that this can (later) also be applied to the entire todo.txt file, converting the actions retroactively, like rendermarkers.

diff --git a/actions/add b/actions/add
--- a/actions/add
+++ b/actions/add
@@ -31,36 +31,13 @@ shift
     exit
 }
 
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 3; }
+
 # Note: We only offer the canonicalization of the date for add and actions based
 # on add, but not for all other actions that modify tasks (e.g. append, replace,
 # etc.) This is meant as a convenient shortcut when adding new tasks; existing
 # task markers should be modified through dedicated actions (e.g. schedule).
-task=$*
-markers=$(echo "$task" | grep -o '[^ ]*[[:graph:]]:\(([^)]\+)\|[^ ]\+\)' | grep '^[[:graph:]]:')
-IFS=$'\n'
-for marker in $markers
-do
-    originalDateString=${marker#[[:graph:]]:}
-    dateString=${originalDateString#(}
-    dateString=${dateString%)}
-
-    if [[ "$dateString" =~ ^[0-9]+$ ]]; then
-        # 'date' also accepts numbers (and always interprets them as the current
-        # day), but numbers should represent ITEM# for task references here.
-        continue
-    fi
-
-    canonicalDate=$(date -d "$dateString" +%F 2>/dev/null) || continue
-    [ "$canonicalDate" = "$originalDateString" ] && continue
-
-    # Multiple human dates (e.g. "today", "now", and especially all time
-    # specifications) resolve to the current day. Don't canonicalize them unless
-    # "today" is used.
-    [ "$originalDateString" != 'today' ] && [ "$canonicalDate" = "$(date +%F)" ] && continue
-
-
-    task=${task/${marker}/${marker:0:2}${canonicalDate}}
-done
-unset IFS
+task="$("${scriptDir}/renderrelativemarkers" --task "$*")" || exit $?
 
 "$TODO_FULL_SH" command ${ADDACTION:-add} "$task"
