Refactoring: Move usage to shell script, separate birdseye.py in lib/

diff --git a/actions/birdseye b/actions/birdseye
--- a/actions/birdseye
+++ b/actions/birdseye
@@ -1,216 +1,43 @@
-#!/usr/bin/env python
-# pylint: disable=global-statement,invalid-name,missing-function-docstring
+#!/bin/bash
+###############################################################################
+##
+# FILE:         birdseye
+# PRODUCT:      todo.txt-cli-ex
+# AUTHOR:       Ingo Karkat <ingo@karkat.de>
+# DATE CREATED: 19-Mar-2024
+#
+###############################################################################
+# CONTENTS:
+#
+# REMARKS:
+#
+# COPYRIGHT: (C) 2024 Ingo Karkat
+#   This program is free software; you can redistribute it and/or modify it
+#   under the terms of the GNU General Public License.
+#   See http://www.gnu.org/copyleft/gpl.txt
+#
+# @(#)birdseye	$Id$	todo.txt-cli-ex
+###############################################################################
 
-""" TODO.TXT Bird's Eye View Reporter
-USAGE NOTES:
-    Works on the raw, unfiltered text files referenced by $TODO_FILE and $DONE_FILE.
-    See more on todo.txt here: http://todotxt.com
+action=$1
+shift
 
-OUTPUT:
-    Displays a list of:
-    - working projects and their percentage complete
-    - contexts in which open todo's exist
-    - contexts and projects with tasks that have been prioritized
-    - projects which are completely done (don't have any open todo's)
-"""
+[ "$action" = "usage" ] && {
+    echo "    $(basename $0) [(open|completed|all)-(projects|contexts) [...]]"
+    echo "      Show a textual report of open and completed tasks"
+    echo "      for all projects and contexts."
+    echo ""
+    exit
+}
 
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly libDir="${projectDir}/lib"
 
-import math
-import os
-import sys
-
-__author__ = "Gina Trapani (ginatrapani@gmail.com)"
-__copyright__ = "Copyright 2006-2024, Gina Trapani"
-__license__ = "GPL"
-
-
-def usage():
-    print(f'    {os.path.basename(sys.argv[0])} [(open|completed|all)-(projects|contexts) [...]]')
-    print("      Show a textual report of open and completed tasks")
-    print("      for all projects and contexts")
-    print("      Works on the unfiltered tasks of TODO_FILE and DONE_FILE.")
-    print("")
-
-
-def printTaskGroups(title, taskDict, priorityList, percentages, taskNum):
-    print("")
-    print(title)
-    if not taskDict:
-        print('No items to list.')
-        return
-
-    itemMaxLength = len(max(taskDict, key=len))
-
-    # Sort first by number of tasks descending, then by case-insensitive item name.
-    items = sorted(list(taskDict.items()), key=lambda x: (-1 * x[1], x[0].casefold()))
-
-    separator('-', (33 if items[0][0] in percentages else 15) + itemMaxLength)
-
-    priorityItems, nonPriorityItems = [], []
-    for item in items:
-        (priorityItems if item[0] in priorityList else nonPriorityItems).append(item)
-
-    def printItemTaskGroup(item, star):
-        printTaskGroup(item, itemMaxLength, percentages.get(item[0], -1), star, taskNum)
-
-    for item in priorityItems:
-        printItemTaskGroup(item, "*")
-    for item in nonPriorityItems:
-        printItemTaskGroup(item, " ")
-
-
-def printTaskGroup(p, pMaxLen, pctage, star, taskNum):
-    taskWidth = int(math.ceil(math.log(taskNum, 10)))
-    taskPlural = " " if p[1] == 1 else "s"
-    pctageWidget = ''
-    if pctage > -1:
-        progressBar = "=" * int(pctage // 10)
-        pctageWidget = f' {pctage:3d}% [{progressBar:10s}]'
-
-    print(f'{star}{pctageWidget} {p[0]:{pMaxLen}s} ({p[1]:{taskWidth}d} task{taskPlural})')
-
-
-SEP_WIDTH = 0
-
-
-def separator(c, width):
-    global SEP_WIDTH
-    SEP_WIDTH = max([width, SEP_WIDTH])
-    print(c * SEP_WIDTH)
-
-
-def process(filespec, sigil, tasks, completed, priority):
-    with open(filespec, "r") as f:
-        taskNum = 0
-        for line in f:
-            prioritized = False
-            words = line.split()
-            if not words:
-                continue
-            if words[0] == "X":
-                continue    # Ignore trashed tasks.
-
-            taskNum += 1
-            if words[0].startswith("("):
-                prioritized = True
-
-            if words[0] == ("x"):
-                for word in words:
-                    wordWithSigil = getWordWithSigil(word, sigil)
-                    if wordWithSigil:
-                        completed[wordWithSigil] = completed.setdefault(wordWithSigil, 0) + 1
-            else:
-                for word in words:
-                    wordWithSigil = getWordWithSigil(word, sigil)
-                    if wordWithSigil:
-                        tasks[wordWithSigil] = tasks.setdefault(wordWithSigil, 0) + 1
-                        if prioritized:
-                            priority.append(wordWithSigil)
-        return taskNum
-
-
-if (os.environ['TODOTXT_SIGIL_BEFORE_PATTERN']
-        or os.environ['TODOTXT_SIGIL_VALID_PATTERN'] != '.*'
-        or os.environ['TODOTXT_SIGIL_AFTER_PATTERN']):
-    import re
-
-    def bre_to_pcre(bre_pattern):
-        pcre_pattern = bre_pattern
-        pcre_pattern = re.sub(r'\\([][(){}+?.*])', r'\1', pcre_pattern)
-        pcre_pattern = re.sub(r'\\([<>])', r'\b', pcre_pattern)
-        return pcre_pattern
-
-    PATTERNS = []
-    if os.environ['TODOTXT_SIGIL_BEFORE_PATTERN']:
-        BEFORE_PATTERN = re.compile('^' + bre_to_pcre(os.environ['TODOTXT_SIGIL_BEFORE_PATTERN']))
-        PATTERNS.append(lambda word, _: BEFORE_PATTERN.sub('', word))
-    if os.environ['TODOTXT_SIGIL_AFTER_PATTERN']:
-        AFTER_PATTERN = re.compile(bre_to_pcre(os.environ['TODOTXT_SIGIL_AFTER_PATTERN']) + '$')
-        PATTERNS.append(lambda word, _: AFTER_PATTERN.sub('', word))
-    if os.environ['TODOTXT_SIGIL_VALID_PATTERN']:
-        def extractValid(word, sigil):
-            match = re.match(re.escape(sigil) + bre_to_pcre(os.environ['TODOTXT_SIGIL_VALID_PATTERN']) + '$', word)
-            if match:
-                return match.group(0)
-            return None
-        PATTERNS.append(extractValid)
-
-    def getWordWithSigil(word, sigil):
-        for pattern in PATTERNS:
-            word = pattern(word, sigil)
-        return word
-else:
-    def getWordWithSigil(word, sigil):
-        return word if word[0:1] == sigil and len(word) > 1 else None
-
-
-def gather(sigil, tasks, completed, priority):
-    taskNum = process(os.environ['TODO_FILE'], sigil, tasks, completed, priority)
-    doneNum = process(os.environ['DONE_FILE'], sigil, completed, completed, priority)
-    return taskNum, doneNum
-
-
-def run(sigil, sigilDescription, isPrintOpen, isPrintCompleted):
-    tasks = {}
-    completed = {}
-    priority = []
-    taskNum, doneNum = gather(sigil, tasks, completed, priority)
-
-    if isPrintOpen:
-        percentages = {}
-        for task in tasks:
-            openTasks = tasks[task]
-            closedTasks = completed.get(task, 0)
-            totalTasks = openTasks + closedTasks
-            percentages[task] = int((closedTasks * 100) / totalTasks)
-
-        printTaskGroups(f"{sigilDescription} with open tasks (* = prioritized)", tasks, priority, percentages, taskNum)
-
-    if isPrintCompleted:
-        tasksWithNoIncompletes = {}
-        for task in completed:
-            if task not in tasks:
-                tasksWithNoIncompletes[task] = completed[task]
-
-        printTaskGroups(f'completed {sigilDescription} (no open tasks)', tasksWithNoIncompletes, [], {}, taskNum + doneNum)
-
-
-def main(argv):
-    if len(argv) == 0 or argv[0] == 'usage':
-        usage()
-        return
-    if len(argv) == 1:
-        argv += ['all-projects', 'open-contexts']
-
-    try:
-        for arg in argv[1:]:
-            isPrintOpen = False
-            isPrintCompleted = False
-
-            selector, axis = arg.split('-')
-            if selector == 'open':
-                isPrintOpen = True
-            elif selector == 'completed':
-                isPrintCompleted = True
-            elif selector == 'all':
-                isPrintOpen = isPrintCompleted = True
-            else:
-                raise ValueError("Invalid selector: " + selector)
-
-            if axis == 'projects':
-                run('+', axis, isPrintOpen, isPrintCompleted)
-            elif axis == 'contexts':
-                run('@', axis, isPrintOpen, isPrintCompleted)
-            else:
-                raise ValueError("Invalid axis: " + axis)
-    except ValueError as e:
-        print(e)
-        usage()
-        sys.exit(2)
-    except Exception as e:  # pylint: disable=broad-except
-        print(e)
-        sys.exit(1)
-
-
-if __name__ == "__main__":
-    main(sys.argv[1:])
+"${libDir}/birdseye.py" "$@"; status=$?
+if [ $status -eq 2 ]; then
+    echo
+    "${BASH_SOURCE[0]}" usage
+fi >&2
+exit $status
