did: BUG: Reimplementation: Comment template is not expanded
Because I forgot to apply the implementation in my do extension to the did action. Looks like other things are missing, too: The cascading to linked tasks, trashing of to-be-killed or contradependent tasks.
It's far more maintainable to delegate to the do extension. Let's do this by offering a TODOTXT_DO_COMMAND hook that allow to inject our own did implementation, pass along the parsed off doneDate[Span] as TODOTXT_DID_DATE[SPAN], and invoke via TODOTXT_DO_COMMAND='did --launch', replacing the "command do".

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/actions/did b/actions/did
--- a/actions/did
+++ b/actions/did
@@ -11,17 +11,13 @@
 #
 # REMARKS:
 #
-# COPYRIGHT: (C) 2010-2025 Ingo Karkat
+# COPYRIGHT: (C) 2010-2026 Ingo Karkat
 #   This program is free software; you can redistribute it and/or modify it
 #   under the terms of the GNU General Public License.
 #   See http://www.gnu.org/copyleft/gpl.txt
 #
 # @(#)did	$Id$	todo.txt-cli-ex
 ###############################################################################
-
-readonly CACHE_DIRSPEC="${XDG_CACHE_HOME:-${HOME}/.cache}"
-[ -d "$CACHE_DIRSPEC" ] || mkdir --parents -- "$CACHE_DIRSPEC" || { printf >&2 'ERROR: Could not initialize cache store at %s\n' "$CACHE_DIRSPEC"; exit 3; }
-: ${TODOTXT_DO_LAST:=${CACHE_DIRSPEC}/todo-lastdone}
 
 action=$1
 shift
@@ -42,6 +38,36 @@ shift
 
 errmsg="usage: $TODO_SH $(basename $0) NR [NR ...] [on] DATE | after DATESPAN | the same|next day [COMMENT]"
 [ $# -eq 0 ] && die "$errmsg"
+
+if [ "$1" = --launch ]; then
+    shift
+    [ -n "${TODOTXT_DID_DATE+t}" ] || { echo >&2 'ASSERT: TODOTXT_DID_DATE is defined'; exit 3; }
+    [ -n "${TODOTXT_DID_DATESPAN+t}" ] || { echo >&2 'ASSERT: TODOTXT_DID_DATESPAN is defined'; exit 3; }
+
+    for item in ${*//,/ }
+    do
+        if [ -z "$TODOTXT_DID_DATE" ]; then
+            addDate=$(sed -e "$item!d" -e 's/^\((.) \|x [0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} \)\{0,1\}\(\([0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\}\) \)\{0,1\}.*$/\3/' "$TODO_FILE")
+            if [ ! "$addDate" ]; then
+                die "TODO: Cannot use date span; no date was included when $item was added."
+            fi
+            TODOTXT_DID_DATE=$(date -d "${addDate}${TODOTXT_DID_DATESPAN:+ }${TODOTXT_DID_DATESPAN}" +%F) || exit 1
+        fi
+
+        getTodo "$item"
+        # Do not check if this item has already been done; this allows
+        # retroactive changes to the done date.
+        # remove priority once item is done
+        sed -i.bak $item"s/^(.) //" "$TODO_FILE" || exit $?
+        sed -i.bak $item's|^\(x [0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} \)\{0,1\}|'"x $TODOTXT_DID_DATE |" "$TODO_FILE" || exit $?
+        if [ $TODOTXT_VERBOSE -gt 0 ]; then
+            getNewtodo "$item"
+            echo "$item $newtodo"
+            echo "TODO: $item marked as done on ${TODOTXT_DID_DATE}."
+        fi
+    done
+    exit 0
+fi
 
 items=
 doneDate=
@@ -74,48 +100,11 @@ else
     shift
 fi
 
-printf '' > "$TODOTXT_DO_LAST"
-for item in ${items//,/ }
-do
-    if [ ! "$doneDate" ]; then
-        addDate=$(sed -e "$item!d" -e 's/^\((.) \|x [0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} \)\{0,1\}\(\([0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\}\) \)\{0,1\}.*$/\3/' "$TODO_FILE")
-        if [ ! "$addDate" ]; then
-            die "TODO: Cannot use date span; no date was included when $item was added."
-        fi
-        doneDate=$(date -d "${addDate}${doneDateSpan:+ }${doneDateSpan}" +%F) || exit 1
-    fi
-
-    if [ "$*" ]; then
-        "$TODO_FULL_SH" command append $item "$@" || exit $?
-    fi
-
-    # We could delegate to the built-in 'do' followed by 'replace', but the
-    # 'replace' command doesn't handle done tasks, and may do surprising things
-    # to existing priorities and dates. This also would have confusing output.
-    getTodo "$item"
-    if [ "${todo:0:2}" = 'X ' ]; then
-        die "TODO: $item is already marked as trashed."
-    fi
-    # Do not check if this item has already been done; this allows
-    # retroactive changes to the done date.
-    # remove priority once item is done
-    sed -i.bak $item"s/^(.) //" "$TODO_FILE" || exit $?
-    sed -i.bak $item's|^\(x [0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} \)\{0,1\}|'"x $doneDate |" "$TODO_FILE" || exit $?
-    if [ $TODOTXT_VERBOSE -gt 0 ]; then
-        getNewtodo "$item"
-        echo "$item $newtodo"
-        echo "TODO: $item marked as done on $doneDate."
-    fi
-    printf '%s ' $item >> "$TODOTXT_DO_LAST"
-
-    if [ -x "$TODO_ACTIONS_DIR/unwait" ]; then
-        # Unblock tasks that depended on the now done task.
-        "$TODO_FULL_SH" unwait 'for' $item 2>&1 | grep -v '^TODO: No tasks that contain the dependent tasks found.$'
-        : # Always exit with a successful exit code even when the command complained.
-    fi
-
-    if [ -x "$TODO_ACTIONS_DIR/recur" ]; then
-        "$TODO_FULL_SH" recur $item apply
-        : # Always exit with a successful exit code even when the command complained.
-    fi
-done
+# We could delegate to the built-in 'do' followed by 'replace', but the
+# 'replace' command doesn't handle done tasks, and may do surprising things
+# to existing priorities and dates. This also would have confusing output.
+# Instead, use a hook inside my 'do' extension that overrides the built-in do.
+TODOTXT_DID_DATE="$doneDate" \
+TODOTXT_DID_DATESPAN="$doneDateSpan" \
+TODOTXT_DO_COMMAND='did --launch' \
+    "$TODO_FULL_SH" do $items "$@"
