Refactoring: Move ~/.todo-lastdone to ~/.cache/todo-lastdone
Use the XDG cache directory to de-clutter the home directory.
Define a TODOTXT_DO_LAST environment variable that can be overwritten.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/actions/did b/actions/did
--- a/actions/did
+++ b/actions/did
@@ -11,13 +11,17 @@
 #
 # REMARKS:
 #
-# COPYRIGHT: (C) 2010-2023 Ingo Karkat
+# COPYRIGHT: (C) 2010-2025 Ingo Karkat
 #   This program is free software; you can redistribute it and/or modify it
 #   under the terms of the GNU General Public License.
 #   See http://www.gnu.org/copyleft/gpl.txt
 #
 # @(#)did	$Id$	todo.txt-cli-ex
 ###############################################################################
+
+readonly CACHE_DIRSPEC="${XDG_CACHE_HOME:-${HOME}/.cache}"
+[ -d "$CACHE_DIRSPEC" ] || mkdir --parents -- "$CACHE_DIRSPEC" || { printf >&2 'ERROR: Could not initialize cache store at %s\n' "$CACHE_DIRSPEC"; exit 3; }
+: ${TODOTXT_DO_LAST:=${CACHE_DIRSPEC}/todo-lastdone}
 
 action=$1
 shift
@@ -70,7 +74,7 @@ else
     shift
 fi
 
-printf '' > ~/.todo-lastdone
+printf '' > "$TODOTXT_DO_LAST"
 for item in ${items//,/ }
 do
     if [ ! "$doneDate" ]; then
@@ -102,7 +106,7 @@ do
         echo "$item $newtodo"
         echo "TODO: $item marked as done on $doneDate."
     fi
-    printf '%s ' $item >> ~/.todo-lastdone
+    printf '%s ' $item >> "$TODOTXT_DO_LAST"
 
     if [ -x "$TODO_ACTIONS_DIR/unwait" ]; then
         # Unblock tasks that depended on the now done task.
diff --git a/actions/do b/actions/do
--- a/actions/do
+++ b/actions/do
@@ -11,13 +11,17 @@
 #
 # REMARKS:
 #
-# COPYRIGHT: (C) 2010-2024 Ingo Karkat
+# COPYRIGHT: (C) 2010-2025 Ingo Karkat
 #   This program is free software; you can redistribute it and/or modify it
 #   under the terms of the GNU General Public License.
 #   See http://www.gnu.org/copyleft/gpl.txt
 #
 # @(#)do	$Id$	todo.txt-cli-ex
 ###############################################################################
+
+readonly CACHE_DIRSPEC="${XDG_CACHE_HOME:-${HOME}/.cache}"
+[ -d "$CACHE_DIRSPEC" ] || mkdir --parents -- "$CACHE_DIRSPEC" || { printf >&2 'ERROR: Could not initialize cache store at %s\n' "$CACHE_DIRSPEC"; exit 3; }
+: ${TODOTXT_DO_LAST:=${CACHE_DIRSPEC}/todo-lastdone}
 
 action=$1
 shift
@@ -57,7 +61,7 @@ do
 done
 [ "$items" ] || die "$errmsg"
 
-[ "$RECURSIVE_DO" ] || > ~/.todo-lastdone
+[ "$RECURSIVE_DO" ] || > "$TODOTXT_DO_LAST"
 originalAutoArchive=$TODOTXT_AUTO_ARCHIVE; TODOTXT_AUTO_ARCHIVE=0   # Don't immediately auto-archive; it would interfere with subsequent unblocking, recurrence, and the numbering of additional passed NR, and also trigger multiple times.
 for item in ${items//,/ }
 do
@@ -78,7 +82,7 @@ do
         die "TODO: $item is already marked as trashed."
     else
         "$TODO_FULL_SH" command do $item || exit $?
-        printf '%s ' $item >> ~/.todo-lastdone
+        printf '%s ' $item >> "$TODOTXT_DO_LAST"
     fi
 
 
diff --git a/actions/trash b/actions/trash
--- a/actions/trash
+++ b/actions/trash
@@ -11,13 +11,17 @@
 #
 # REMARKS:
 #
-# COPYRIGHT: (C) 2010-2023 Ingo Karkat
+# COPYRIGHT: (C) 2010-2025 Ingo Karkat
 #   This program is free software; you can redistribute it and/or modify it
 #   under the terms of the GNU General Public License.
 #   See http://www.gnu.org/copyleft/gpl.txt
 #
 # @(#)trash	$Id$	todo.txt-cli-ex
 ###############################################################################
+
+readonly CACHE_DIRSPEC="${XDG_CACHE_HOME:-${HOME}/.cache}"
+[ -d "$CACHE_DIRSPEC" ] || mkdir --parents -- "$CACHE_DIRSPEC" || { printf >&2 'ERROR: Could not initialize cache store at %s\n' "$CACHE_DIRSPEC"; exit 3; }
+: ${TODOTXT_DO_LAST:=${CACHE_DIRSPEC}/todo-lastdone}
 
 action=$1
 shift
@@ -61,7 +65,7 @@ do
 done
 [ "$items" ] || die "$errmsg"
 
-[ "$RECURSIVE_DO" ] || > ~/.todo-lastdone
+[ "$RECURSIVE_DO" ] || > "$TODOTXT_DO_LAST"
 # Split multiple trash's, if comma separated change to whitespace separated.
 # Loop the 'trash' function for each task.
 for item in ${items//,/ }
@@ -102,7 +106,7 @@ do
             # Untrash from trash.txt via 'untrash'.
         else
             # Allow untrashing via 'undo'.
-            printf '%s ' $item >> ~/.todo-lastdone
+            printf '%s ' $item >> "$TODOTXT_DO_LAST"
         fi
         if [ $TODOTXT_VERBOSE -gt 0 ]; then
             if [ "$isHard" ]; then
