did: Implement after DATESPAN, relative to add date.

diff --git a/actions/did b/actions/did
--- a/actions/did
+++ b/actions/did
@@ -16,7 +16,7 @@
 #   under the terms of the GNU General Public License.
 #   See http://www.gnu.org/copyleft/gpl.txt
 #
-# @(#)did	001	(24-Feb-2012)	todo.txt-cli-ex
+# @(#)did	001	(18-Apr-2012)	todo.txt-cli-ex
 ###############################################################################
 
 action=$1
@@ -26,15 +26,20 @@ shift
     echo "    $(basename $0) ITEM#[, ITEM#, ITEM#, ...] [on] DATE [COMMENT]"
     echo "      Marks task(s) on line ITEM# as done at DATE in todo.txt,"
     echo "      optionally appending COMMENT."
+    echo "    $(basename $0) ITEM#[, ITEM#, ITEM#, ...] after DATESPAN [COMMENT]"
+    echo "      Marks task(s) on line ITEM# as done DATESPAN later than the added date,"
+    echo "      optionally appending COMMENT."
     echo "      Task(s) that were dependent on ITEM# have that blocker removed."
     echo ""
     exit
 }
 
-errmsg="usage: $TODO_SH $(basename $0) ITEM#[, ITEM#, ITEM#, ...] [on] DATE [COMMENT]"
+errmsg="usage: $TODO_SH $(basename $0) ITEM#[, ITEM#, ITEM#, ...] [on] DATE | after DATESPAN [COMMENT]"
 [ $# -eq 0 ] && die "$errmsg"
 
 items=
+doneDate=
+doneDateSpan=
 while [[ "$1" =~ ^[,0-9]+$ ]]
 do
     items="$items $1"
@@ -42,24 +47,39 @@ do
 done
 [ "$items" ] || die "$errmsg"
 
-[ "$1" = "on" ] && shift
-[ "$1" ] || die "$errmsg"
-doneDate=$(date -d "$1" +%F) || exit 1
-shift
+if [ "$1" = 'after' ]; then
+    shift
+    [ "$1" ] || die "$errmsg"
+    doneDateSpan=$1
+    shift
+else
+    [ "$1" = 'on' ] && shift
+    [ "$1" ] || die "$errmsg"
+    doneDate=$(date -d "$1" +%F) || exit 1
+    shift
+fi
 
 printf '' > ~/.todo-lastdone
 for item in ${items//,/ }
-do 
+do
+    if [ ! "$doneDate" -a "$doneDateSpan" ]; then
+        addDate=$(sed -e "$item!d" -e 's/^\((.) \|x [0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} \)\{0,1\}\(\([0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\}\) \)\{0,1\}.*$/\3/' "$TODO_FILE")
+        if [ ! "$addDate" ]; then
+            die "TODO: Cannot use date span; no date was included when $item was added."
+        fi
+        doneDate=$(date -d "$addDate $doneDateSpan" +%F) || exit 1
+    fi
+
     if [ $# -gt 0 ]; then
         "$TODO_FULL_SH" command append $item "$@" || exit $?
     fi
 
     # We could delegate to the built-in 'do' followed by 'replace', but the
     # 'replace' command doesn't handle done tasks, and may do surprising things
-    # to existing priorities and dates. This also would have confusing output. 
+    # to existing priorities and dates. This also would have confusing output.
     getTodo "$item"
     # Do not check if this item has already been done; this allows
-    # retroactive changes to the done date. 
+    # retroactive changes to the done date.
     # remove priority once item is done
     sed -i.bak $item"s/^(.) //" "$TODO_FILE"
     sed -i.bak $item's|^\(x [0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} \)\{0,1\}|'"x $doneDate |" "$TODO_FILE"
@@ -71,13 +91,13 @@ do
     printf '%s ' $item >> ~/.todo-lastdone
 
     if [ -x "$TODO_ACTIONS_DIR/unwait" ]; then
-        # Unblock tasks that depended on the now done task. 
+        # Unblock tasks that depended on the now done task.
         "$TODO_FULL_SH" unwait 'for' $item | grep -v '^TODO: No tasks that contain the dependent tasks found.$'
-        : # Always exit with a successful exit code even when the command complained. 
+        : # Always exit with a successful exit code even when the command complained.
     fi
 
     if [ -x "$TODO_ACTIONS_DIR/recur" ]; then
         "$TODO_FULL_SH" recur $item apply
-        : # Always exit with a successful exit code even when the command complained. 
+        : # Always exit with a successful exit code even when the command complained.
     fi
 done
