edit: Minor: Return the non-success exit status from the editor
The echo command accidentally clobbered it.

diff --git a/actions/edit b/actions/edit
--- a/actions/edit
+++ b/actions/edit
@@ -69,7 +69,7 @@ getTodo "$item"
 echo "$todo" > "$TMPEDIT"
 
 TMPMODTIME=$(stat -c %Y "$TMPEDIT")
-"$EDITOR" "$TMPEDIT" || { echo 2>&1 "Unclean exit of editor; aborting!"; exit $?; }
+"$EDITOR" "$TMPEDIT" || { status=$?; echo 2>&1 "Unclean exit of editor; aborting!"; exit $status; }
 NEWMODTIME=$(stat -c %Y "$TMPEDIT")
 
 if [ $NEWMODTIME -eq $TMPMODTIME ]; then
