more compatiblity fixes

diff --git a/actions/recur b/actions/recur
--- a/actions/recur
+++ b/actions/recur
@@ -20,7 +20,6 @@
 #   under the terms of the GNU General Public License.
 #   See http://www.gnu.org/copyleft/gpl.txt
 #
-# @(#)recur	$Id$	todo.txt-cli-ex
 ###############################################################################
 
 action=$1
@@ -107,7 +106,7 @@ if [ "$recur" = 'apply' ]; then
     # - The scheduling marker will be updated by the regular code below.
     # - Finally, when such exists, the user is asked (maybe he wants to
     #   accumulate them) whether the done comment should be removed.
-    today=$(date +%F)
+    today=$("${GNU_PREFIX}"date +%F)
     todo=$("${GNU_PREFIX}"sed -e "$item!d" -e 's/^x [0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} //' -e 's/^\(([A-Z]) \)\{0,1\}[0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} /\1'"${today}"' /' "$TODO_FILE") || exit $?
 fi
 
@@ -122,7 +121,7 @@ case $recur in
         ;;
     *)
         recurType='Next'
-        nextdate=$(date -d "$recur" +%F) || die "TODO: Invalid recurrence date format."
+        nextdate=$("${GNU_PREFIX}"date -d "$recur" +%F) || die "TODO: Invalid recurrence date format."
         recurrence="{${recur}} t:${nextdate}"
         newtodo=$(echo "$todo" | "${GNU_PREFIX}"sed -e 's#[[:space:]]\+t:\([0-9]\{2,4\}[^A-Za-z0-9]\)\{2\}[0-9]\{2,4\}##g' | "${GNU_PREFIX}"sed -e 's#\([[:space:]]\+\){[^}]\+}\([[:space:]]\|$\)#\1'"${recurrence}"'\2#;t' -e 's#$# '"${recurrence}"'#')
         ;;
@@ -135,9 +134,9 @@ fi
 "$TODO_FULL_SH" -T command $command "$newtodo" || exit $?
 
 if [ "$recurType" ]; then
-    today=$(date +%F)   # Need to calculate time differences from midnight.
-    todaySeconds=$(date -d "$today" +%s)
-    nextSeconds=$(date -d "$nextdate" +%s)
+    today=$("${GNU_PREFIX}"date +%F)   # Need to calculate time differences from midnight.
+    todaySeconds=$("${GNU_PREFIX}"date -d "$today" +%s)
+    nextSeconds=$("${GNU_PREFIX}"date -d "$nextdate" +%s)
     recurTimespan=$(((nextSeconds - todaySeconds) / (24 * 3600)))
     case $recurTimespan in
         0)  recurTimespan="that's today!";;
