Print the actually rendered tasks if TODOTXT_VERBOSE >= 1
In scheduledFilter, extract nextTask() so that we have a single place to hook into (also when filtering is skipped due to done or trashed task). Check $TODOTXT_VERBOSE and isOnRaw (so the filter is used as part of the rendermarkers action, not as the usual pre filter), and print the changed task / an empty line (to maintain the correct task numbering; fortunately, the _format() already filters those out for us) to stderr (as a side channel that does not get redirected into the todo file), which gets piped into the _format() API (so we get the usual highlighting).

diff --git a/actions/rendermarkers b/actions/rendermarkers
--- a/actions/rendermarkers
+++ b/actions/rendermarkers
@@ -36,5 +36,15 @@ set -o pipefail
 readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
 [ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 3; }
 
-< "$TODO_FILE" TODOTXT_SCHEDULED_FILTER_ON_RAW_DATA=t "${scriptDir}/../filter/scheduledFilter" "$@" > "${TODO_FILE}.bak" && \
-    mv "${TODO_FILE}.bak" "${TODO_FILE}" || die "Fatal Error: Unable to render markers in tasks."
+renderViaScheduledFilter()
+{
+    < "$TODO_FILE" TODOTXT_SCHEDULED_FILTER_ON_RAW_DATA=t "${scriptDir}/../filter/scheduledFilter" "$@" > "${TODO_FILE}.bak" && \
+    mv "${TODO_FILE}.bak" "${TODO_FILE}"
+}
+if [ $TODOTXT_VERBOSE -gt 0 ]; then
+    TOTAL=$(sed -n '$ =' "$TODO_FILE") || exit $?
+    PADDING=${#TOTAL}
+    { renderViaScheduledFilter "$@" 2>&1 | _format '' "$PADDING"; } || die 'Fatal Error: Unable to render markers in tasks.'
+else
+    renderViaScheduledFilter "$@" || die 'Fatal Error: Unable to render markers in tasks.'
+fi
