rendermarkers: Disable the futureTasks filter for the renderer task output
The user wants to see _all_ rendered tasks here, also those that only are scheduled in the future. We do not completely disable the final filter, as that would also get rid of the helpful (and customary) extra highlighting and date conversion.

diff --git a/actions/rendermarkers b/actions/rendermarkers
--- a/actions/rendermarkers
+++ b/actions/rendermarkers
@@ -44,7 +44,7 @@ renderViaScheduledFilter()
 if [ $TODOTXT_VERBOSE -gt 0 ]; then
     TOTAL=$(sed -n '$ =' "$TODO_FILE") || exit $?
     PADDING=${#TOTAL}
-    { renderViaScheduledFilter "$@" 2>&1 | _format '' "$PADDING"; } || die 'Fatal Error: Unable to render markers in tasks.'
+    { renderViaScheduledFilter "$@" 2>&1 | TODOTXT_FILTER_FUTURE_TASKS=0 _format '' "$PADDING"; } || die 'Fatal Error: Unable to render markers in tasks.'
 else
     renderViaScheduledFilter "$@" || die 'Fatal Error: Unable to render markers in tasks.'
 fi
